language: python
python:
- '3.5'
dist: trusty
os:
- linux
sudo: false
install:
- pip install -r requirements.txt
script:
- python3 setup.py sdist
deploy:
  provider: pypi
  user: liyj
  distributions: sdist
  password:
    secure: qkCHTQQgxnHgVB+rikeUI18jL9QjDdebgy4L4/JBL55Qd+g+UBqX38sVP6j8Ma9Z709l103he5Pm6k0XvX232ZqTUPTCo54USaXxGALaBV2gaGeYi/V7Ey6wAC6OFttcq7/YTZpwb3HWpxASRk9l7EGzouVCMnQGVHy3ERyYohdLxsDEjgndYobK0eb1YCfJUxUIQqUODsPPcKWJ6GakQjqljz1qS6YO9sBiLZP4Oz3kdwELMgBHZJyliDP4plK8awFzSxsTtxEq1NmmPqsujBhldWInjIL0eEW8hHWQ+i7wBd8ozQt+Imxau6mk6jxS+scPyizw0ZdIOq2Iu9H5aC0nqQsFpwECPFZdE1FJf8P91oFhx2ZzuJhp1gVzqhCkL+HZa1lv6x3d4IBkp3bQcjnA0mPHcnuJK5RiB5nfJZkea8Ofm6TAfdCmwr/KtJukv45ZQ7pFdyfitfmJeIW36WbKGT/cecXdU2pH44D0IA8QdbYXNVL6FrrUzzi2sOGAv7TtusBMFyRg0v2H99k6eeMOGmafWdRHgK4ff0TRpKXwy6dSMOwH/rhHqsy9fjhIdgGDMnk1bciITZJqFH0GpKV9jfsz3iZUMRNZVW0OdodGbsT81Qcdn1XvDIpZMi8pHNyGl8P9f9FOxKff9rzfbGsR1oy4l0oATf/qMT4BDWk=
