language: python
python:
- '3.5'
dist: trusty
os:
- linux
sudo: false
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
deploy:
  provider: pypi
  user: liyj
  distributions: sdist
  password:
    secure: i318YEIIrxFwuD9kpgEz6sX3y3aw/FJ7F9w9eCAYKL4OLRW9julGPYKvyadiPZS5eerT+HlCCWl4F2sSQBR2OTHG+s8vnuQgUMBXPWvelF81eaUmSqKlJU4/xihKA6Tfe6fYKjWQj771DlAxSliMDPxEJ1JWvBO78YvOW4ba5LGrXE+rtrJWKa/Msm6E9aNVhvqO/osz8HvjF0jlFTmgem0visuSdBx7uJWdP7SNpZqaUisWK7YN8pPrMi/+1N1KPE4bZlBSmfdVSbAqcY9dHesFHspJ60ZmsLFtOWBUYIfUQAPlbRS+MrJhqjL6hzuJpab0xeaHkNsx/gP5R+3O8Lh+Myg8erMVPzLWILiK3ErcazQHGAPrmcvBiq8qIh8qmPL04LayqsIhuu/CL4RAKiOpx+U0f3pH/UzA6moFGJhikqMtjKdzN3GfYe0ss/nY845H3vfxV5quiska37rloTOiBaeeyqpqVi883g6xO+DmmExbFSDX2XA0ffOR9fyFJNDPnVuL7CIBlbjZ/Njcz0Ax6sM62GUXDolaq2NtDUD455Lh//W6c71BDnXT9rC9hdJBKUIEzPg0/Ej+Ow2hBEEDH+yIX4ufmlASWEsp3zxOjoF352k+F+AvWtfXe+89S+i+1RmS4MfG9/aPNmRqt+eCUa+7Rr843lK+2CMMiFo=
